### PR TITLE
Us143 Export Document as serialized object

### LINKED ISSUE #143: Export as Squeak Document
As a text writer that collaborates with other writers who also use Squeak, I want to be able to export my document directly as a Squeak document, in order to send it to my colleagues.

- [x] There is an option to export as a Squeak document
- [x] That file contains the text with its styles
- [x] That file contains the structures I created

Estimated effort: `5`

### PR DESCRIPTION
**Pull request by konradh**

### CODE REVIEW

**Comment by frcroth** [comment]
Please add tests

**Comment by sirkrypt0** [comment]
Intended to merge into US88?

**Comment by sirkrypt0** [comment]
Why is it no strategy pattern like with export?

**Comment by frcroth** [comment]
> 
> 
> Why is it no strategy pattern like with export?

I guess you could argue with XP / Triangulation. As we only implement one Import Strategy a full pattern would go against these patterns

**Pull request merged**
